# Generated by Django 2.0.6 on 2020-01-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('head0', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('head1', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('head2', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('pub_date', models.DateField(blank=True, default='', null=True)),
                ('thumbnail', models.ImageField(blank=True, default='', null=True, upload_to='blog/images')),
            ],
        ),
    ]
