# Generated by Django 2.0.6 on 2020-01-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='chead0',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='chead1',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='chead2',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head0',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head1',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head2',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
