# Generated by Django 2.0.6 on 2020-01-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=90, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=111, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=111, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=111, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=111, null=True)),
                ('zip_code', models.CharField(blank=True, default='', max_length=111, null=True)),
                ('mobile', models.BigIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
